/*
 * This source file was generated by the Gradle 'init' task
 */
package cl.hcslearning.cxf.soap.client.dynamic;

import org.apache.cxf.endpoint.Client;
import org.apache.cxf.jaxws.endpoint.dynamic.JaxWsDynamicClientFactory;

import java.math.BigInteger;

public class App {

    public static void main(String[] args) throws Exception {
        String wsdlUrl = "https://www.dataaccess.com/webservicesserver/NumberConversion.wso?WSDL";
        JaxWsDynamicClientFactory factory = JaxWsDynamicClientFactory.newInstance();
        Client client = factory.createClient(wsdlUrl);
        Object[] respuesta = client.invoke("NumberToWords", new BigInteger("33"));
        System.out.println("Respuesta: "+respuesta[0]);
    }

}
